name: pack zsh
# auto-task.start-build-time = ?
on: { "push": { "paths": [".github/workflows/pack.yml"] } }
# on: { "schedule": [{ "cron": "11 5 20 1,5,9 *" }] }

env:
  # DEBIAN_FRONTEND: noninteractive
  ZSH_REPO: ghcr.io/2moe/zsh-static

jobs:
  # pack:
    # strategy:
    #   fail-fast: true
    #   matrix: ${{ fromJson(vars.JSON).matrix }}
      ## matrix:
      ##   arch:
      ##    - x64

    # runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     shell: zsh --pipefail -fex {0}
    # steps:
    #   - name: install zsh builder
    #     shell: sh -e {0}
    #     run: docker run --pull=always --rm -v /bin:/host -w /opt/bin ${{env.ZSH_REPO}}:builder-x64 cp zsh builder /host/

    #   - name: Login to GHCR
    #     uses: docker/login-action@v3
    #     with:
    #       registry: ghcr.io
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITHUB_TOKEN }}

    #   - uses: actions/checkout@v4
    #     with:
    #       ref: dev

    #   - name: build & push
    #     run: |
    #       /bin/builder --version
    #       /bin/builder --arch ${{matrix.arch}} --push

    #   - name: compress to zstd
    #     run: |
    #       rm -rfv tmp ||:
    #       mkdir -p tmp/a
    #       docker export $(docker create ${{env.ZSH_REPO}}:${{matrix.arch}}) > tmp/a.tar
    #       cd tmp
    #       tar -C a -xf a.tar
    #       mkdir -p a/usr/bin
    #       ln -svf /opt/bin/zsh a/usr/bin/sh
    #       run_tar=(
    #         sudo tar
    #         --use-compress-program='zstdmt -18v'
    #         --posix
    #         --owner=root --group=root --numeric-owner
    #         --exclude=.dockerenv
    #         -C a
    #         -cf zsh-${{matrix.arch}}.tar.zst
    #         .
    #       )
    #       $run_tar

    #   - name: set title
    #     run: printf "%s\n" "TITLE=$(date --utc +%Y-%m-%d)" >>$GITHUB_ENV

    #   - name: release
    #     uses: softprops/action-gh-release@v1
    #     with:
    #       fail_on_unmatched_files: true
    #       tag_name: latest
    #       name: ${{env.TITLE}}
    #       files: |
    #         tmp/*.zst
  manifest:
    # needs: pack
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: zsh --pipefail -fex {0}
    steps:
      - name: install zsh builder
        shell: sh -e {0}
        run: docker run --pull=always --rm -v /bin:/host -w /opt/bin ${{env.ZSH_REPO}}:builder-x64 cp zsh builder /host/

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: test json
        shell: node {0}
        run: |
          const s = JSON.parse(`${{vars.JSON}}`).matrix.arch.join(",")
          console.log(s)
          const fs = require('fs')
          fs.appendFileSync(`${process.env.GITHUB_ENV}`, `ARCHS=${s}\n`, 'utf8')

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: create manifest
        run: |
          cmd=(
            /bin/builder --push
            manifest
            --archs ${{env.ARCHS}}
            --latest
            --date
          )
          $cmd
