name: pack zsh
# auto-task.start-build-time = ?
# on: { "push": { "paths": [".github/workflows/pack.yml"] } }
on: { "schedule": [{ "cron": "11 5 20 1,5,9 *" }] }

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: zsh --pipefail -fex {0}
    env:
      ZSH_REPO: ghcr.io/2moe/zsh-static:builder-x64
    steps:
      - name: install zsh
        shell: sh -e {0}
        run: docker run --rm -v /bin:/host -w /opt/bin ${{env.ZSH_REPO}} cp zsh builder /host/

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 1

      - name: build & push
        run: ./src/build
