name: build zsh-builder
# auto-task.start-build-time = ?
on: { "push": { "paths": [".github/workflows/rs.yml"] } }

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          ref: dev
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        env:
          CARGO_TARGET_DIR: /tmp/rs
        run: |
          cargo b -r
          install -Dm755 /tmp/rs/release/build-zsh-docker tmp.dk/builder
          cp assets/builder/Dockerfile tmp.dk

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: tmp.dk
          push: true
          tags: ghcr.io/2moe/zsh-static:builder-x64
